name: flutter_text_helpers
description: A widget collection which simplifies the usage of Text() and TextField(). No need to use Theme.of(context) to access textTheme elements like bodytext1 or headline1, etc. Also provides shortcuts for color and fontSize.
version: 2.0.0
homepage: https://gitlab.com/ad-on-is/flutter_text_helpers

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
      sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

flutter:
